apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: peddireddy
  labels:
    "name": "hari"
    "course": "devops"
    "year": "2024"
  annotations:
    "name.year.com": "2023"
    "gcr.io.image.id": "devops1"
spec:
  containers:
    - name: labels-pod
      image: nginx

