apiVersion: v1
kind: Pod
metadata:
  name: pullpolicy
  namespace: peddireddy
spec:
  containers:
    - name: image-pull
      image: nginx
      imagePullPolicy: Always
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "256Mi"