apiVersion: v1
kind: Pod
metadata:
  name: configreference
  namespace: peddireddy
spec:
  containers:
    - name: pod1
      image: nginx
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: course
      - name: duration
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: duration
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: trainer