apiVersion: v1
kind: Pod
metadata:
  name: config-direct
  namespace: peddireddy
spec:
  containers:
    - name: config-pod
      image: nginx
      envFrom:
      - configMapRef:
          name: course-config