apiVersion: v1
kind: Pod
metadata:
  name: secret-map
  namespace: peddireddy
spec:
  containers:
    - name: secret-pod
      image: nginx
      env:
      - name: username
        valueFrom:
          secretKeyRef:
            name: secret-file
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: secret-file
            key: password