apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-pod
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
      app: nginx
      tier: frontend
  template:
    metadata:
      labels:
        env: production
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
