apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-pod
  labels:
    tier: web-tier
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
      app: web
      tier: frontend
  template:
    metadata:
      labels:
        env: production
        app: web
        tier: frontend
    spec:
      container:
      - name: replica-cont
        image: nginx
        ports:
        - name: nginx-service-port
          containerPort: 83
---
apiVersion: v1
kind: Service
metadata:
  name: robo-shop-deploy
  labels:
    app: front-end
    tier: deploy
spec:
  type: NodePort
  selector:
    env: production
    app: web
    tier: frontend
  ports:
  - name: nodeport-service
    protocol: "TCP"
    port: 8083
    targetPort: 83