---
- name: nginx installation
  hosts: localhost
  become: true
  tasks:
  - name: nginx install
    apt:
      name: nginx
      state: present
  - name: start service
    service:
      name: nginx
      state: started